name: Build and deploy unified Node.js app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Login to Azure
        uses: azure/login@v2 #v2 is correct but linter is wrong
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5FB39170F5F5497D838E451B12A90262 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_710BCEE4FB9940259FD9F28CFBB2E8A6 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C1E1054924B1418EBDFF248CA73BE36A }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3 #v3 is correct but linter is wrong
        id: deploy-to-webapp
        with:
          app-name: 'web-app-guide'
          slot-name: 'Production'
          package: .
